apiVersion: v1
kind: ConfigMap
metadata:
  name: pedidos-config
  namespace: pedidos-veloz
data:
  DB_HOST: postgres
  DB_NAME: pedidosdb
  DB_USER: postgres
  PEDIDOS_URL: http://pedidos:5000
  PAGAMENTOS_URL: http://pagamentos:5001
  ESTOQUE_URL: http://estoque:5002
